---
- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: yes
  vars:
    k8s_version: "1.28.5"
    pod_network_cidr: "10.244.0.0/16"
  tasks:
    - name: Initialize cluster with kubeadm
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --service-cidr=10.96.0.0/12 --kubernetes-version=v{{ k8s_version }} --apiserver-advertise-address={{ ansible_default_ipv4.address }} --apiserver-cert-extra-sans={{ ansible_hostname }}
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for admin user
      ansible.builtin.file:
        path: /home/admin/.kube
        state: directory
        owner: admin
        group: admin
        mode: 0755

    - name: Copy admin config to user directory
      ansible.builtin.command:
        cmd: cp -i /etc/kubernetes/admin.conf /home/admin/.kube/config
      changed_when: false
    - name: Chown kube config
      ansible.builtin.file:
        path: /home/admin/.kube/config
        owner: admin
        group: admin

    - name: Extract join command
      ansible.builtin.set_fact:
        join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join .*? --token .*? --discovery-token-ca-cert-hash .*?', multiline=true) }}"

    - name: Save join command to file
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: /tmp/k8s_join_command.txt
        mode: 0644

    - name: Display join command
      ansible.builtin.debug:
        msg: "Join command: {{ join_command }}"

    - name: Wait for Kubernetes API
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 6443
        delay: 10
        timeout: 120
