---
- name: Install Calico network plugin
  hosts: k8s_master
  become: no  # Запускаем от admin с kubectl
  tasks:
    - name: Apply Calico manifest
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml

    - name: Wait for Calico pods
      ansible.builtin.command: kubectl wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s

    - name: Wait for all system pods
      ansible.builtin.command: kubectl wait --for=condition=ready pod --all -n kube-system --timeout=300s

    - name: Check cluster status
      ansible.builtin.command: kubectl get nodes -o wide
      register: cluster_status

    - name: Display cluster status
      ansible.builtin.debug:
        msg: "{{ cluster_status.stdout }}"

    - name: Check system pods
      ansible.builtin.command: kubectl get pods -n kube-system
      register: system_pods

    - name: Display system pods
      ansible.builtin.debug:
        msg: "{{ system_pods.stdout }}"
